#!/bin/bash

echo "🔧 Исправление прав доступа для обхода Sandbox проблем"
echo "====================================================="
echo ""
echo "⚠️  ВНИМАНИЕ: Эта команда требует пароль администратора (sudo)"
echo ""
echo "Выполните следующие команды в терминале:"
echo ""
echo "1. Исправить права на DerivedData:"
echo "   sudo chown -R \$(whoami) ~/XcodeDerivedData/"
echo "   sudo chmod -R u+w ~/XcodeDerivedData/"
echo ""
echo "2. Исправить права на проект:"
echo "   sudo chown -R \$(whoami) ~/uzbekservice_app/ios/"
echo "   sudo chmod -R u+w ~/uzbekservice_app/ios/"
echo ""
echo "3. Исправить права на build директорию:"
echo "   sudo chown -R \$(whoami) ~/uzbekservice_app/build/"
echo "   sudo chmod -R u+w ~/uzbekservice_app/build/"
echo ""
echo "После выполнения команд:"
echo "1. Полностью закройте Xcode (Cmd + Q)"
echo "2. Откройте проект заново"
echo "3. Попробуйте Archive снова"
echo ""

