import '../models/firestore_models.dart';

/// Сервис для работы с тестовыми данными
/// Используется когда Firestore недоступен или есть проблемы с правами
class TestDataService {
  static final List<FirestoreUser> _testSpecialists = [
    // Барберы
    FirestoreUser(
      id: 'test_specialist_1',
      phoneNumber: '+998901234567',
      name: 'Алишер Усманов',
      userType: 'specialist',
      category: 'barber',
      description: 'Опытный барбер с 5-летним стажем. Специализируюсь на классических и современных стрижках. Работаю с любыми типами волос.',
      pricePerHour: 50000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=12',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.2995, 'lng': 69.2401},
      skills: ['Стрижка', 'Бритье', 'Укладка', 'Окрашивание'],
      rating: 4.8,
      totalOrders: 127,
    ),
    FirestoreUser(
      id: 'test_specialist_5',
      phoneNumber: '+998901234571',
      name: 'Дмитрий Ковалев',
      userType: 'specialist',
      category: 'barber',
      description: 'Мастер мужских стрижек премиум-класса. Работаю в стиле барбершоп. Индивидуальный подход к каждому клиенту.',
      pricePerHour: 60000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=13',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 15)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.3050, 'lng': 69.2450},
      skills: ['Мужские стрижки', 'Борода', 'Усы', 'Бритье опасной бритвой'],
      rating: 4.9,
      totalOrders: 89,
    ),
    FirestoreUser(
      id: 'test_specialist_6',
      phoneNumber: '+998901234572',
      name: 'Иван Петров',
      userType: 'specialist',
      category: 'barber',
      description: 'Молодой талантливый барбер. Слежу за последними трендами в мужских стрижках. Быстро и качественно.',
      pricePerHour: 45000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=14',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      updatedAt: DateTime.now(),
      isVerified: false,
      location: {'lat': 41.3150, 'lng': 69.2550},
      skills: ['Модные стрижки', 'Фейды', 'Укладка'],
      rating: 4.6,
      totalOrders: 45,
    ),
    // Няни
    FirestoreUser(
      id: 'test_specialist_2',
      phoneNumber: '+998901234568',
      name: 'Мария Петрова',
      userType: 'specialist',
      category: 'nanny',
      description: 'Профессиональная няня с медицинским образованием. Опыт работы с детьми от 0 до 12 лет. Развивающие занятия, прогулки, уход.',
      pricePerHour: 40000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=47',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 45)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.3100, 'lng': 69.2500},
      skills: ['Уход за детьми', 'Развивающие игры', 'Первая помощь', 'Подготовка к школе'],
      rating: 4.9,
      totalOrders: 89,
    ),
    FirestoreUser(
      id: 'test_specialist_7',
      phoneNumber: '+998901234573',
      name: 'Анна Смирнова',
      userType: 'specialist',
      category: 'nanny',
      description: 'Опытная няня с педагогическим образованием. Специализируюсь на работе с дошкольниками. Развивающие методики, творческие занятия.',
      pricePerHour: 45000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=45',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 25)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.3200, 'lng': 69.2600},
      skills: ['Дошкольное развитие', 'Творчество', 'Чтение', 'Логика'],
      rating: 4.8,
      totalOrders: 112,
    ),
    // Мастера по дому
    FirestoreUser(
      id: 'test_specialist_3',
      phoneNumber: '+998901234569',
      name: 'Сергей Иванов',
      userType: 'specialist',
      category: 'handyman',
      description: 'Мастер на все руки - электрика, сантехника, ремонт. Быстрое решение любых бытовых проблем. Гарантия на все работы.',
      pricePerHour: 60000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=15',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 20)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.3200, 'lng': 69.2600},
      skills: ['Электрика', 'Сантехника', 'Ремонт мебели', 'Установка техники'],
      rating: 4.7,
      totalOrders: 156,
    ),
    FirestoreUser(
      id: 'test_specialist_8',
      phoneNumber: '+998901234574',
      name: 'Александр Волков',
      userType: 'specialist',
      category: 'handyman',
      description: 'Профессиональный электрик. Монтаж и ремонт электропроводки, установка розеток, выключателей, светильников. Безопасно и качественно.',
      pricePerHour: 55000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=16',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 35)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.3250, 'lng': 69.2650},
      skills: ['Электромонтаж', 'Ремонт проводки', 'Установка освещения'],
      rating: 4.9,
      totalOrders: 203,
    ),
    FirestoreUser(
      id: 'test_specialist_9',
      phoneNumber: '+998901234575',
      name: 'Михаил Соколов',
      userType: 'specialist',
      category: 'handyman',
      description: 'Сантехник с большим опытом. Устранение протечек, замена труб, установка сантехники. Работаю аккуратно, без грязи.',
      pricePerHour: 58000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=17',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 28)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.3300, 'lng': 69.2700},
      skills: ['Сантехника', 'Устранение протечек', 'Установка сантехники'],
      rating: 4.8,
      totalOrders: 178,
    ),
    // Строители
    FirestoreUser(
      id: 'test_specialist_4',
      phoneNumber: '+998901234570',
      name: 'Анна Козлова',
      userType: 'specialist',
      category: 'construction',
      description: 'Руководитель строительной бригады. Полный цикл строительных работ: от проектирования до отделки. Качественные материалы, соблюдение сроков.',
      pricePerHour: 80000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=20',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 60)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.3300, 'lng': 69.2700},
      skills: ['Строительство', 'Ремонт', 'Дизайн', 'Отделка'],
      rating: 4.6,
      totalOrders: 203,
    ),
    FirestoreUser(
      id: 'test_specialist_10',
      phoneNumber: '+998901234576',
      name: 'Владимир Новиков',
      userType: 'specialist',
      category: 'construction',
      description: 'Опытный строитель. Кладка, штукатурка, покраска, укладка плитки. Работаю один и с бригадой. Гарантия качества.',
      pricePerHour: 70000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=18',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 40)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.3350, 'lng': 69.2750},
      skills: ['Кладка', 'Штукатурка', 'Плитка', 'Покраска'],
      rating: 4.7,
      totalOrders: 145,
    ),
    FirestoreUser(
      id: 'test_specialist_11',
      phoneNumber: '+998901234577',
      name: 'Елена Морозова',
      userType: 'specialist',
      category: 'construction',
      description: 'Дизайнер-отделочник. Современный дизайн интерьеров, качественная отделка. Помогу создать уютный и стильный дом.',
      pricePerHour: 75000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=21',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 18)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.3400, 'lng': 69.2800},
      skills: ['Дизайн интерьеров', 'Отделка', 'Декорирование'],
      rating: 4.9,
      totalOrders: 67,
    ),
    // Дополнительные специалисты
    FirestoreUser(
      id: 'test_specialist_12',
      phoneNumber: '+998901234578',
      name: 'Олег Лебедев',
      userType: 'specialist',
      category: 'handyman',
      description: 'Универсальный мастер. Ремонт мебели, сборка, установка дверей и окон. Быстро и недорого.',
      pricePerHour: 50000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=19',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 12)),
      updatedAt: DateTime.now(),
      isVerified: false,
      location: {'lat': 41.3000, 'lng': 69.2400},
      skills: ['Ремонт мебели', 'Сборка', 'Установка'],
      rating: 4.5,
      totalOrders: 34,
    ),
    // Сантехники
    FirestoreUser(
      id: 'test_specialist_13',
      phoneNumber: '+998901234579',
      name: 'Рустам Каримов',
      userType: 'specialist',
      category: 'plumber',
      description: 'Опытный сантехник. Устранение протечек, замена труб, установка смесителей, унитазов, раковин. Работаю быстро и аккуратно.',
      pricePerHour: 55000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=22',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 50)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.3050, 'lng': 69.2450},
      skills: ['Устранение протечек', 'Замена труб', 'Установка сантехники', 'Канализация'],
      rating: 4.8,
      totalOrders: 234,
    ),
    FirestoreUser(
      id: 'test_specialist_14',
      phoneNumber: '+998901234580',
      name: 'Бахтияр Норов',
      userType: 'specialist',
      category: 'plumber',
      description: 'Сантехник с 10-летним стажем. Прочистка канализации, установка бойлеров, ремонт стиральных машин. Гарантия на работу.',
      pricePerHour: 60000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=23',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 80)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.3100, 'lng': 69.2500},
      skills: ['Прочистка канализации', 'Бойлеры', 'Стиральные машины'],
      rating: 4.9,
      totalOrders: 312,
    ),
    // Электрики
    FirestoreUser(
      id: 'test_specialist_15',
      phoneNumber: '+998901234581',
      name: 'Андрей Федоров',
      userType: 'specialist',
      category: 'electrician',
      description: 'Профессиональный электрик. Монтаж проводки, установка розеток и выключателей, подключение люстр, ремонт электрики.',
      pricePerHour: 65000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=24',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 45)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.3150, 'lng': 69.2550},
      skills: ['Монтаж проводки', 'Розетки', 'Выключатели', 'Освещение'],
      rating: 4.9,
      totalOrders: 267,
    ),
    FirestoreUser(
      id: 'test_specialist_16',
      phoneNumber: '+998901234582',
      name: 'Тимур Рахимов',
      userType: 'specialist',
      category: 'electrician',
      description: 'Электрик высокой квалификации. Работа с электрощитками, установка счетчиков, автоматов. Сертифицированный специалист.',
      pricePerHour: 70000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=25',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 60)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.3200, 'lng': 69.2600},
      skills: ['Электрощитки', 'Счетчики', 'Автоматы', 'Заземление'],
      rating: 4.8,
      totalOrders: 189,
    ),
    // Ремонт бытовой техники
    FirestoreUser(
      id: 'test_specialist_17',
      phoneNumber: '+998901234583',
      name: 'Максим Орлов',
      userType: 'specialist',
      category: 'appliance_repair',
      description: 'Мастер по ремонту бытовой техники. Холодильники, стиральные машины, посудомоечные машины, кондиционеры.',
      pricePerHour: 60000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=26',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 55)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.3250, 'lng': 69.2650},
      skills: ['Холодильники', 'Стиральные машины', 'Кондиционеры', 'Посудомойки'],
      rating: 4.7,
      totalOrders: 198,
    ),
    FirestoreUser(
      id: 'test_specialist_18',
      phoneNumber: '+998901234584',
      name: 'Дамир Юсупов',
      userType: 'specialist',
      category: 'appliance_repair',
      description: 'Ремонт телевизоров, микроволновок, пылесосов. Быстрая диагностика, качественный ремонт. Выезд на дом.',
      pricePerHour: 55000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=27',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 35)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.3300, 'lng': 69.2700},
      skills: ['Телевизоры', 'Микроволновки', 'Пылесосы', 'Мелкая техника'],
      rating: 4.6,
      totalOrders: 145,
    ),
    // Домработницы
    FirestoreUser(
      id: 'test_specialist_19',
      phoneNumber: '+998901234585',
      name: 'Наталья Кузнецова',
      userType: 'specialist',
      category: 'housekeeper',
      description: 'Опытная домработница. Генеральная и ежедневная уборка, глажка, приготовление пищи. Ответственная и аккуратная.',
      pricePerHour: 40000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=48',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 70)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.3350, 'lng': 69.2750},
      skills: ['Уборка', 'Глажка', 'Готовка', 'Стирка'],
      rating: 4.9,
      totalOrders: 287,
    ),
    FirestoreUser(
      id: 'test_specialist_20',
      phoneNumber: '+998901234586',
      name: 'Светлана Белова',
      userType: 'specialist',
      category: 'housekeeper',
      description: 'Профессиональная уборка квартир и домов. Мою окна, чищу ковры, убираю после ремонта. Свои моющие средства.',
      pricePerHour: 45000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=49',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 40)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.3400, 'lng': 69.2800},
      skills: ['Генеральная уборка', 'Мытье окон', 'Чистка ковров', 'Уборка после ремонта'],
      rating: 4.8,
      totalOrders: 156,
    ),
    // Репетиторы
    FirestoreUser(
      id: 'test_specialist_21',
      phoneNumber: '+998901234587',
      name: 'Ирина Семенова',
      userType: 'specialist',
      category: 'tutor',
      description: 'Репетитор по математике и физике. Подготовка к ЕГЭ, ОГЭ, олимпиадам. 15 лет опыта преподавания.',
      pricePerHour: 80000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=50',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 90)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.2900, 'lng': 69.2300},
      skills: ['Математика', 'Физика', 'Подготовка к экзаменам', 'Олимпиады'],
      rating: 5.0,
      totalOrders: 342,
    ),
    FirestoreUser(
      id: 'test_specialist_22',
      phoneNumber: '+998901234588',
      name: 'Джон Смит',
      userType: 'specialist',
      category: 'tutor',
      description: 'Native English teacher. IELTS, TOEFL preparation. Business English, conversational classes.',
      pricePerHour: 100000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=51',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 120)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.2950, 'lng': 69.2350},
      skills: ['English', 'IELTS', 'TOEFL', 'Business English'],
      rating: 4.9,
      totalOrders: 278,
    ),
    FirestoreUser(
      id: 'test_specialist_23',
      phoneNumber: '+998901234589',
      name: 'Алексей Попов',
      userType: 'specialist',
      category: 'tutor',
      description: 'Репетитор по программированию. Python, JavaScript, веб-разработка. Обучаю с нуля до уровня junior.',
      pricePerHour: 90000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=52',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.3000, 'lng': 69.2400},
      skills: ['Python', 'JavaScript', 'Веб-разработка', 'Алгоритмы'],
      rating: 4.8,
      totalOrders: 89,
    ),
    // Психологи
    FirestoreUser(
      id: 'test_specialist_24',
      phoneNumber: '+998901234590',
      name: 'Екатерина Волкова',
      userType: 'specialist',
      category: 'psychologist',
      description: 'Клинический психолог. Работаю с тревожностью, депрессией, семейными проблемами. Индивидуальные и семейные консультации.',
      pricePerHour: 120000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=53',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 100)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.3050, 'lng': 69.2450},
      skills: ['Тревожность', 'Депрессия', 'Семейная терапия', 'Личностный рост'],
      rating: 5.0,
      totalOrders: 198,
    ),
    FirestoreUser(
      id: 'test_specialist_25',
      phoneNumber: '+998901234591',
      name: 'Дмитрий Зайцев',
      userType: 'specialist',
      category: 'psychologist',
      description: 'Детский психолог. Помогаю детям и подросткам справляться с трудностями. Работа с родителями.',
      pricePerHour: 100000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=54',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 75)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.3100, 'lng': 69.2500},
      skills: ['Детская психология', 'Подростки', 'Коррекция поведения', 'Консультации родителей'],
      rating: 4.9,
      totalOrders: 156,
    ),
    // Услуги переезда
    FirestoreUser(
      id: 'test_specialist_26',
      phoneNumber: '+998901234592',
      name: 'Виктор Сидоров',
      userType: 'specialist',
      category: 'moving',
      description: 'Услуги переезда под ключ. Упаковка, погрузка, транспортировка, разгрузка. Бережное отношение к вещам.',
      pricePerHour: 50000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=55',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 65)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.3150, 'lng': 69.2550},
      skills: ['Квартирный переезд', 'Офисный переезд', 'Упаковка', 'Грузчики'],
      rating: 4.7,
      totalOrders: 234,
    ),
    FirestoreUser(
      id: 'test_specialist_27',
      phoneNumber: '+998901234593',
      name: 'Артем Николаев',
      userType: 'specialist',
      category: 'moving',
      description: 'Грузоперевозки по городу и области. Газели, фургоны разного размера. Помощь грузчиков.',
      pricePerHour: 45000.0,
      avatarUrl: 'https://i.pravatar.cc/150?img=56',
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      createdAt: DateTime.now().subtract(const Duration(days: 50)),
      updatedAt: DateTime.now(),
      isVerified: true,
      location: {'lat': 41.3200, 'lng': 69.2600},
      skills: ['Грузоперевозки', 'Газель', 'Фургон', 'Междугородние перевозки'],
      rating: 4.6,
      totalOrders: 312,
    ),
  ];

  static final Map<String, List<FirestoreSpecialistService>> _testServices = {
    'test_specialist_1': [
      FirestoreSpecialistService(
        id: 'service_1',
        specialistId: 'test_specialist_1',
        name: 'Мужская стрижка',
        description: 'Классическая стрижка с укладкой',
        price: 50000,
        durationMinutes: 30,
        category: 'barber',
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
        updatedAt: DateTime.now(),
      ),
      FirestoreSpecialistService(
        id: 'service_2',
        specialistId: 'test_specialist_1',
        name: 'Стрижка + борода',
        description: 'Стрижка волос и оформление бороды',
        price: 80000,
        durationMinutes: 45,
        category: 'barber',
        createdAt: DateTime.now().subtract(const Duration(days: 4)),
        updatedAt: DateTime.now(),
      ),
      FirestoreSpecialistService(
        id: 'service_3',
        specialistId: 'test_specialist_1',
        name: 'Детская стрижка',
        description: 'Стрижка для детей с игровой атмосферой',
        price: 40000,
        durationMinutes: 25,
        category: 'barber',
        createdAt: DateTime.now().subtract(const Duration(days: 3)),
        updatedAt: DateTime.now(),
      ),
    ],
    'test_specialist_2': [
      FirestoreSpecialistService(
        id: 'service_1',
        specialistId: 'test_specialist_2',
        name: 'Няня на вечер',
        description: 'Уход за ребенком на вечернее время',
        price: 70000,
        durationMinutes: 240,
        category: 'nanny',
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
        updatedAt: DateTime.now(),
      ),
      FirestoreSpecialistService(
        id: 'service_2',
        specialistId: 'test_specialist_2',
        name: 'Няня на полный день',
        description: 'Полный день заботы и развивающих игр',
        price: 120000,
        durationMinutes: 480,
        category: 'nanny',
        createdAt: DateTime.now().subtract(const Duration(days: 4)),
        updatedAt: DateTime.now(),
      ),
    ],
  };

  /// Получить всех тестовых специалистов
  static List<FirestoreUser> getTestSpecialists() {
    return List.from(_testSpecialists);
  }

  /// Получить услуги специалиста (тестовые данные)
  static List<FirestoreSpecialistService> getTestServicesForSpecialist(String specialistId) {
    final services = _testServices[specialistId];
    if (services != null) {
      return services
          .map((service) => service.copyWith(
                createdAt: service.createdAt,
                updatedAt: DateTime.now(),
              ))
          .toList();
    }
    // дефолтный набор услуг
    return [
      FirestoreSpecialistService(
        id: 'service_default_1',
        specialistId: specialistId,
        name: 'Консультация',
        description: 'Первичная консультация',
        price: 30000,
        durationMinutes: 30,
        category: 'general',
        createdAt: DateTime.now().subtract(const Duration(days: 2)),
        updatedAt: DateTime.now(),
      ),
      FirestoreSpecialistService(
        id: 'service_default_2',
        specialistId: specialistId,
        name: 'Основная услуга',
        description: 'Основной пакет услуг',
        price: 60000,
        durationMinutes: 60,
        category: 'general',
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
        updatedAt: DateTime.now(),
      ),
    ];
  }

  /// Получить специалистов по категории
  static List<FirestoreUser> getTestSpecialistsByCategory(String category) {
    return _testSpecialists.where((s) => s.category == category).toList();
  }

  /// Поиск специалистов по местоположению
  static List<FirestoreUser> searchTestSpecialistsByLocation({
    required double lat,
    required double lng,
    required double radiusKm,
    String? category,
  }) {
    List<FirestoreUser> results = _testSpecialists;
    
    if (category != null) {
      results = results.where((s) => s.category == category).toList();
    }
    
    // Простая фильтрация по расстоянию (для тестирования)
    return results.where((specialist) {
      if (specialist.location == null) return false;
      
      final location = specialist.location!;
      final specialistLat = (location['lat'] ?? location['latitude']) as double;
      final specialistLng = (location['lng'] ?? location['longitude']) as double;
      
      // Простой расчет расстояния (не точный, но для тестирования подойдет)
      final distance = ((lat - specialistLat).abs() + (lng - specialistLng).abs()) * 111; // примерное расстояние в км
      
      return distance <= radiusKm;
    }).toList();
  }

  /// Создать тестового пользователя
  static FirestoreUser createTestUser({
    required String phoneNumber,
    required String name,
    required String userType,
    String? category,
    String? description,
    double? pricePerHour,
  }) {
    return FirestoreUser(
      id: 'test_user_${DateTime.now().millisecondsSinceEpoch}',
      phoneNumber: phoneNumber,
      name: name,
      userType: userType,
      category: category,
      description: description,
      pricePerHour: pricePerHour,
      deviceTokens: const [],
      notificationPreferences: const {'push': true, 'sms': true, 'email': true},
      avatarUrl: null,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      isVerified: false,
      location: {'lat': 41.2995, 'lng': 69.2401}, // Ташкент по умолчанию
      skills: category != null ? _getDefaultSkills(category) : null,
      rating: 0.0,
      totalOrders: 0,
    );
  }

  /// Получить навыки по умолчанию для категории
  static List<String> _getDefaultSkills(String category) {
    switch (category) {
      case 'barber':
        return ['Стрижка', 'Бритье', 'Укладка'];
      case 'nanny':
        return ['Уход за детьми', 'Развивающие игры', 'Первая помощь'];
      case 'handyman':
        return ['Электрика', 'Сантехника', 'Ремонт'];
      case 'construction':
        return ['Строительство', 'Ремонт', 'Отделка'];
      case 'plumber':
        return ['Устранение протечек', 'Замена труб', 'Установка сантехники'];
      case 'electrician':
        return ['Монтаж проводки', 'Розетки', 'Освещение'];
      case 'appliance_repair':
        return ['Холодильники', 'Стиральные машины', 'Кондиционеры'];
      case 'housekeeper':
        return ['Уборка', 'Глажка', 'Готовка'];
      case 'tutor':
        return ['Обучение', 'Подготовка к экзаменам', 'Репетиторство'];
      case 'psychologist':
        return ['Консультации', 'Терапия', 'Психологическая помощь'];
      case 'moving':
        return ['Переезд', 'Грузчики', 'Перевозка'];
      default:
        return ['Общие услуги'];
    }
  }
}